export interface CatalogProduct {
  id: string;
  name: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  category: string;
  subcategory: string | null;
  brand: string;
  modelKey: string;
  color: string;
  colorLabel: string;
  colorHex: string;
  image: string;
  sizes: string[];
  stock: number;
  rating: number;
  reviewsCount: number;
}

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "new-balance-530-beige",
    name: "New Balance 530 Beige",
    description:
      "Women's New Balance 530 mirror original in beige and moonbeam tones, with a retro running shape, breathable mesh panels, synthetic overlays, and cushioned comfort for daily wear.",
    price: 1950,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-530",
    color: "Beige",
    colorLabel: "Beige / Moonbeam",
    colorHex: "#D8CCB8",
    image: "/products/deroma-new-balance-530-beige.jpg",
    sizes: ["36", "37", "38", "39", "40", "41"],
    stock: 8,
    rating: 4.9,
    reviewsCount: 142,
  },
  {
    id: "new-balance-530-white",
    name: "New Balance 530 White Silver",
    description:
      "Women's New Balance 530 mirror original in white and silver, built around a 2000s running silhouette with mesh ventilation, layered synthetic leather, and a lightweight cushioned sole.",
    price: 1950,
    compareAtPrice: 3500,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-530",
    color: "White",
    colorLabel: "White / Silver",
    colorHex: "#F8F8F2",
    image: "/products/deroma-new-balance-530-white.png",
    sizes: ["37", "38", "39", "40"],
    stock: 9,
    rating: 4.7,
    reviewsCount: 88,
  },
  {
    id: "new-balance-327-burgundy",
    name: "New Balance 327 Burgundy Moonbeam",
    description:
      "New Balance 327 mirror original with oversized N branding, suede and nylon upper, lugged outsole edge, and a burgundy moonbeam colorway for clean lifestyle outfits.",
    price: 1450,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-327",
    color: "Burgundy",
    colorLabel: "Burgundy / Moonbeam",
    colorHex: "#7A2230",
    image: "/products/deroma-new-balance-327-burgundy.png",
    sizes: ["36", "38", "39", "41"],
    stock: 7,
    rating: 4.5,
    reviewsCount: 34,
  },
  {
    id: "new-balance-9060-pastel-pink",
    name: "New Balance 9060 Sea Salt Pink",
    description:
      "Women's New Balance 9060 mirror original in sea salt, cream, and pink tones, featuring a chunky sculpted midsole, mesh upper, and layered suede-style panels.",
    price: 2100,
    compareAtPrice: 4100,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-9060",
    color: "Pastel Pink",
    colorLabel: "Sea Salt / Pink",
    colorHex: "#F0B8B8",
    image: "/products/deroma-new-balance-9060-pastel-pink.png",
    sizes: ["36", "37", "38", "39", "40", "41"],
    stock: 6,
    rating: 4.8,
    reviewsCount: 210,
  },
  {
    id: "adidas-handball-spezial-burgundy",
    name: "Adidas Handball Spezial Burgundy Gum",
    description:
      "Adidas Handball Spezial mirror original in burgundy suede finish with white three stripes, gum outsole, lace closure, and low-profile vintage terrace styling.",
    price: 1800,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "Adidas",
    modelKey: "adidas-handball-spezial",
    color: "Burgundy",
    colorLabel: "Burgundy / Gum",
    colorHex: "#6F1F2D",
    image: "/products/deroma-adidas-handball-spezial-burgundy.png",
    sizes: ["38", "39", "40"],
    stock: 8,
    rating: 4.3,
    reviewsCount: 19,
  },
  {
    id: "nike-v2k-run-pink",
    name: "Nike V2K Run White Pink Foam",
    description:
      "Women's Nike V2K Run mirror original with white mesh, pink foam accents, retro runner overlays, dual-density midsole, and durable rubber traction for all-day comfort.",
    price: 1650,
    compareAtPrice: 3200,
    category: "shoes",
    subcategory: null,
    brand: "Nike",
    modelKey: "nike-v2k-run",
    color: "Pink",
    colorLabel: "White / Pink Foam",
    colorHex: "#F2AFC3",
    image: "/products/deroma-nike-v2k-run-pink.png",
    sizes: ["36", "37", "38", "39", "40", "41"],
    stock: 9,
    rating: 4.9,
    reviewsCount: 328,
  },
  {
    id: "nike-v2k-run-brown",
    name: "Nike V2K Run Light Orewood Brown",
    description:
      "Nike V2K Run mirror original in light orewood brown and beige, with layered runner styling, breathable mesh, plastic-look accents, and cushioned daily comfort.",
    price: 1650,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "Nike",
    modelKey: "nike-v2k-run",
    color: "Brown",
    colorLabel: "Light Orewood / Brown",
    colorHex: "#8B735D",
    image: "/products/deroma-nike-v2k-run-brown.png",
    sizes: ["37", "38", "39", "40"],
    stock: 7,
    rating: 4.6,
    reviewsCount: 75,
  },
  {
    id: "adidas-campus-00s-grey",
    name: "Adidas Campus 00s Grey White",
    description:
      "Adidas Campus 00s mirror original in grey suede finish with white stripes, padded chunky tongue, thick rubber sole, and Y2K skate-inspired profile.",
    price: 1950,
    compareAtPrice: 3500,
    category: "shoes",
    subcategory: null,
    brand: "Adidas",
    modelKey: "adidas-campus-00s",
    color: "Grey",
    colorLabel: "Grey / White",
    colorHex: "#8E8E86",
    image: "/products/deroma-adidas-campus-00s-grey.png",
    sizes: ["36", "37", "39", "40", "41"],
    stock: 8,
    rating: 4.8,
    reviewsCount: 154,
  },
  {
    id: "adidas-samba-og-white-navy",
    name: "Adidas Samba OG White Navy Gum",
    description:
      "Adidas Samba OG mirror original in white and navy with a gum sole, low-profile leather upper, suede toe overlay, and classic gold Samba side branding.",
    price: 1750,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "Adidas",
    modelKey: "adidas-samba-og",
    color: "Navy",
    colorLabel: "White / Navy",
    colorHex: "#1F365D",
    image: "/products/deroma-adidas-samba-og-white-navy.png",
    sizes: ["38", "39", "40"],
    stock: 10,
    rating: 4.4,
    reviewsCount: 42,
  },
  {
    id: "adidas-campus-00s-beige",
    name: "Adidas Campus 00s Beige White",
    description:
      "Adidas Campus 00s mirror original in beige with white three stripes, soft suede upper, padded collar, chunky 00s proportions, and a clean gum-edge outsole.",
    price: 1950,
    compareAtPrice: 4200,
    category: "shoes",
    subcategory: null,
    brand: "Adidas",
    modelKey: "adidas-campus-00s",
    color: "Beige",
    colorLabel: "Beige / White",
    colorHex: "#D8CAB3",
    image: "/products/deroma-adidas-campus-00s-beige.png",
    sizes: ["36", "37", "38", "39", "40", "41"],
    stock: 9,
    rating: 4.7,
    reviewsCount: 112,
  },
  {
    id: "new-balance-327-navy",
    name: "New Balance 327 Navy Moonbeam",
    description:
      "New Balance 327 mirror original in navy and moonbeam, with oversized side N branding, retro wedge profile, suede overlays, and grippy lugged outsole detailing.",
    price: 1450,
    compareAtPrice: 1800,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-327",
    color: "Navy",
    colorLabel: "Navy / Moonbeam",
    colorHex: "#242A56",
    image: "/products/deroma-new-balance-327-navy.png",
    sizes: ["37", "38", "39"],
    stock: 7,
    rating: 4.5,
    reviewsCount: 28,
  },
  {
    id: "asics-gel-kayano-14-pink",
    name: "ASICS Gel-Kayano 14 Pink",
    description:
      "ASICS Gel-Kayano 14 mirror original in soft pink with white tiger stripes, breathable mesh, layered synthetic panels, and retro running support inspired by the 2000s.",
    price: 1600,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "ASICS",
    modelKey: "asics-gel-kayano-14",
    color: "Pink",
    colorLabel: "Pink / White",
    colorHex: "#D9A6C3",
    image: "/products/deroma-asics-gel-kayano-14-pink.png",
    sizes: ["36", "37", "38", "39", "40", "41"],
    stock: 6,
    rating: 4.9,
    reviewsCount: 412,
  },
  {
    id: "new-balance-530-silver",
    name: "New Balance 530 Silver Metallic",
    description:
      "New Balance 530 mirror original in silver metallic and white, combining mesh breathability, metallic overlays, and a cushioned retro runner sole for daily styling.",
    price: 1950,
    compareAtPrice: 3500,
    category: "shoes",
    subcategory: null,
    brand: "New Balance",
    modelKey: "new-balance-530",
    color: "Silver",
    colorLabel: "Silver / White",
    colorHex: "#C4C8CE",
    image: "/products/deroma-new-balance-530-silver.png",
    sizes: ["36", "38", "40", "41"],
    stock: 8,
    rating: 4.8,
    reviewsCount: 180,
  },
  {
    id: "adidas-handball-spezial-cream-burgundy",
    name: "Adidas Handball Spezial Cream Burgundy",
    description:
      "Adidas Handball Spezial mirror original in cream with burgundy stripes, suede upper, gum outsole, and vintage indoor court styling for everyday outfits.",
    price: 1800,
    compareAtPrice: null,
    category: "shoes",
    subcategory: null,
    brand: "Adidas",
    modelKey: "adidas-handball-spezial",
    color: "Cream Burgundy",
    colorLabel: "Cream / Burgundy",
    colorHex: "#E7DDC7",
    image: "/products/deroma-adidas-handball-spezial-cream-burgundy.png",
    sizes: ["37", "38", "39", "40", "41"],
    stock: 8,
    rating: 4.2,
    reviewsCount: 15,
  },
];

export const CATALOG_PRODUCT_IDS = CATALOG_PRODUCTS.map((product) => product.id);
