import prisma from "@/lib/prisma";
import { requireAdmin } from "@/lib/adminAuth";
import { CalendarDays, ClipboardList } from "lucide-react";
import { formatCurrency } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function DailyLogPage({ searchParams }: { searchParams: Promise<{ date?: string }> }) {
  await requireAdmin();
  const params = await searchParams;
  const date = params.date || new Date().toISOString().slice(0, 10);
  const start = new Date(`${date}T00:00:00`);
  const end = new Date(start); end.setDate(end.getDate() + 1);
  let orders: Array<{ orderNumber: string; customerName: string; status: string; totalPrice: unknown; createdAt: Date }> = [];
  try { orders = await prisma.order.findMany({ where: { createdAt: { gte: start, lt: end } }, orderBy: { createdAt: "desc" } }); } catch (error) { console.warn("Unable to load daily log", error); }
  const revenue = orders.filter((order) => order.status !== "cancelled").reduce((sum, order) => sum + Number(order.totalPrice), 0);
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#D8B46A]">Operations journal</p><h1 className="mt-1 font-playfair text-3xl font-black">Daily log</h1><p className="mt-1 text-xs text-[#6B1F2A]/65">Jump to any day and review its orders and performance.</p></div><form className="flex items-center gap-2"><input name="date" type="date" defaultValue={date} className="rounded-xl border border-[#942E3A]/15 bg-white px-3 py-2.5 text-xs" /><button className="rounded-xl bg-[#942E3A] px-3 py-2.5 text-xs font-bold text-[#FFF9EB]">View day</button></form></div><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl border border-[#942E3A]/10 bg-white p-3"><p className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Orders</p><p className="mt-1 font-playfair text-2xl font-black">{orders.length}</p></div><div className="rounded-2xl border border-[#D8B46A]/35 bg-[#fff7df] p-3"><p className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Revenue</p><p className="mt-1 font-playfair text-xl font-black">{formatCurrency(revenue)}</p></div><div className="rounded-2xl border border-[#942E3A]/10 bg-white p-3"><p className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Pending</p><p className="mt-1 font-playfair text-2xl font-black">{orders.filter((order) => order.status === "pending").length}</p></div></div><section className="rounded-3xl border border-[#942E3A]/10 bg-white p-4 shadow-sm sm:p-6"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#D8B46A]" /><h2 className="font-playfair text-xl font-bold">Orders on {new Date(`${date}T12:00:00`).toLocaleDateString("en-US", { dateStyle: "full" })}</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="border-b border-[#942E3A]/10 text-[10px] uppercase tracking-wide text-[#6B1F2A]/55"><tr><th className="pb-3">Time</th><th className="pb-3">Order</th><th className="pb-3">Customer</th><th className="pb-3">Status</th><th className="pb-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-[#942E3A]/8">{orders.map((order) => <tr key={order.orderNumber}><td className="py-3 text-[#6B1F2A]/65">{order.createdAt.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</td><td className="py-3 font-bold text-[#942E3A]">{order.orderNumber}</td><td className="py-3 text-[#6B1F2A]">{order.customerName}</td><td className="py-3 capitalize text-[#942E3A]">{order.status}</td><td className="py-3 text-right font-bold text-[#942E3A]">{formatCurrency(Number(order.totalPrice))}</td></tr>)}</tbody></table>{orders.length === 0 && <p className="py-12 text-center text-xs text-[#6B1F2A]/60"><ClipboardList className="mx-auto mb-2 h-6 w-6 text-[#D8B46A]" />No orders on this date.</p>}</div></section></div>;
}
