import Link from "next/link";
import { ArrowLeft, Building2, CalendarDays, FileText, Package, Wallet } from "lucide-react";
import { notFound } from "next/navigation";
import prisma from "@/lib/prisma";
import { requireAdmin } from "@/lib/adminAuth";
import { formatCurrency } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function PurchaseInvoiceDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin();
  const { id } = await params;
  const invoice = await prisma.purchaseInvoice.findUnique({ where: { id }, include: { supplier: true, items: { include: { product: true, variant: true, lot: true } } } });
  if (!invoice) notFound();
  const balance = Number(invoice.total) - Number(invoice.amountPaid);
  return <div className="mx-auto max-w-6xl space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><Link href="/admin/suppliers" className="rounded-xl border border-[#942E3A]/15 bg-white p-2 text-[#942E3A]"><ArrowLeft className="h-4 w-4" /></Link><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#D8B46A]">Purchase invoice</p><h1 className="mt-1 font-playfair text-3xl font-black">{invoice.invoiceNumber}</h1></div></div><span className="w-fit rounded-full bg-[#FFF9EB] px-3 py-2 text-[10px] font-bold capitalize text-[#942E3A]">{invoice.status.replace("_", " ")}</span></div>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-3xl bg-[#942E3A] p-6 text-[#FFF9EB] sm:p-8"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#D8B46A] text-[#942E3A]"><FileText /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#D8B46A]">Supplier invoice</p><h2 className="mt-1 font-playfair text-3xl font-black">{invoice.supplier.name}</h2><p className="mt-2 text-xs text-white/70">{invoice.supplier.phone || "No supplier phone"} {invoice.supplier.email ? `· ${invoice.supplier.email}` : ""}</p></div></div><div className="mt-7 grid gap-3 text-xs sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><CalendarDays className="h-4 w-4 text-[#D8B46A]" /><p className="mt-2 text-white/65">Invoice date</p><p className="mt-1 font-bold">{invoice.invoiceDate.toLocaleDateString("en-US", { dateStyle: "medium" })}</p></div><div className="rounded-2xl bg-white/10 p-4"><Building2 className="h-4 w-4 text-[#D8B46A]" /><p className="mt-2 text-white/65">Reference</p><p className="mt-1 truncate font-bold">{invoice.reference || "Not provided"}</p></div><div className="rounded-2xl bg-white/10 p-4"><Package className="h-4 w-4 text-[#D8B46A]" /><p className="mt-2 text-white/65">Units received</p><p className="mt-1 font-bold">{invoice.items.reduce((sum, item) => sum + item.quantity, 0)}</p></div></div></div><div className="rounded-3xl border border-[#D8B46A]/35 bg-[#fff7df] p-6 shadow-sm sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#D8B46A]">Financial summary</p><div className="mt-5 space-y-3 text-xs text-[#6B1F2A]"><p className="flex justify-between"><span>Products subtotal</span><strong>{formatCurrency(Number(invoice.subtotal))}</strong></p><p className="flex justify-between"><span>Shipping</span><strong>{formatCurrency(Number(invoice.shippingCost))}</strong></p><p className="flex justify-between text-emerald-700"><span>Discount</span><strong>-{formatCurrency(Number(invoice.discount))}</strong></p><p className="flex justify-between border-t border-[#942E3A]/15 pt-3 text-lg font-black text-[#942E3A]"><span>Total</span><strong>{formatCurrency(Number(invoice.total))}</strong></p><p className="flex justify-between"><span>Paid</span><strong>{formatCurrency(Number(invoice.amountPaid))}</strong></p><p className="flex justify-between font-bold text-[#942E3A]"><span>Balance</span><strong>{formatCurrency(balance)}</strong></p></div></div></section>
    <section className="rounded-3xl border border-[#942E3A]/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><Package className="h-4 w-4 text-[#D8B46A]" /><h2 className="font-playfair text-xl font-bold">Received products</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-[#942E3A]/10 text-[10px] uppercase tracking-wide text-[#6B1F2A]/55"><tr><th className="pb-3">Product</th><th className="pb-3">Variant / SKU</th><th className="pb-3">Quantity</th><th className="pb-3">Wholesale unit</th><th className="pb-3">Selling unit</th><th className="pb-3">Remaining</th><th className="pb-3 text-right">Line total</th></tr></thead><tbody className="divide-y divide-[#942E3A]/8">{invoice.items.map((item) => <tr key={item.id}><td className="py-4 font-bold text-[#942E3A]"><Link href={`/admin/products/${item.productId}`} className="hover:underline">{item.product.name}</Link></td><td className="py-4 text-[#6B1F2A]/70">{item.variant.color} · {item.variant.size}<br /><span className="text-[10px]">{item.variant.sku}</span></td><td className="py-4 text-[#6B1F2A]">{item.quantity}</td><td className="py-4 text-[#6B1F2A]">{formatCurrency(Number(item.wholesalePrice))}</td><td className="py-4 text-[#6B1F2A]">{formatCurrency(Number(item.retailPrice))}</td><td className="py-4 font-bold text-[#D8B46A]">{item.lot?.remaining ?? item.quantity}</td><td className="py-4 text-right font-bold text-[#942E3A]">{formatCurrency(Number(item.lineTotal))}</td></tr>)}</tbody></table></div>{invoice.notes && <div className="mt-5 rounded-2xl bg-[#FFF9EB] p-4 text-xs text-[#6B1F2A]/75"><p className="font-bold text-[#942E3A]">Invoice notes</p><p className="mt-1">{invoice.notes}</p></div>}</section>
  </div>;
}
