"use client";

import Link from "next/link";
import { Building2, FileText, Mail, MapPin, Phone, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { createSupplierAction, deleteSupplierAction } from "@/app/admin/suppliers/actions";
import { formatCurrency } from "@/lib/utils";

export type SupplierCard = { id: string; name: string; phone: string | null; email: string | null; address: string | null; notes: string | null; productCount: number; invoiceCount: number; invoiceTotal: number };
export type InvoiceCard = { id: string; invoiceNumber: string; supplierId: string; supplierName: string; invoiceDate: string; status: string; total: number; itemCount: number };

const tabs = ["suppliers", "invoices"] as const;

export default function AdminSuppliersWorkspace({ suppliers, invoices }: { suppliers: SupplierCard[]; invoices: InvoiceCard[] }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("suppliers");
  const [showModal, setShowModal] = useState(false);
  const isInvoices = tab === "invoices";

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#D8B46A]">Procurement</p><h1 className="mt-1 font-playfair text-3xl font-black">{isInvoices ? "Purchase invoices" : "Suppliers"}</h1><p className="mt-1 text-xs text-[#6B1F2A]/65">{isInvoices ? "Track every shipment, cost, payment, and stock receipt." : "Your supplier relationships, purchasing history, and stock sources."}</p></div>
        <button type="button" onClick={() => isInvoices ? window.location.assign("/admin/suppliers/invoices/new") : setShowModal(true)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#942E3A] px-4 py-3 text-xs font-bold text-[#FFF9EB] shadow-sm transition hover:bg-[#7e2732] sm:w-auto"><Plus className="h-4 w-4 text-[#D8B46A]" /> {isInvoices ? "Create new invoice" : "Add supplier"}</button>
      </div>

      <div className="flex w-full gap-2 rounded-2xl border border-[#942E3A]/10 bg-white p-2 shadow-sm sm:w-fit"><button type="button" onClick={() => setTab("suppliers")} className={`inline-flex flex-1 items-center justify-center gap-2 rounded-xl px-5 py-2.5 text-xs font-bold transition sm:flex-none ${!isInvoices ? "bg-[#942E3A] text-[#FFF9EB]" : "text-[#942E3A]/65 hover:bg-[#FFF9EB]"}`}><Building2 className="h-4 w-4" /> Suppliers <span className="rounded-full bg-[#D8B46A]/25 px-1.5 text-[9px]">{suppliers.length}</span></button><button type="button" onClick={() => setTab("invoices")} className={`inline-flex flex-1 items-center justify-center gap-2 rounded-xl px-5 py-2.5 text-xs font-bold transition sm:flex-none ${isInvoices ? "bg-[#942E3A] text-[#FFF9EB]" : "text-[#942E3A]/65 hover:bg-[#FFF9EB]"}`}><FileText className="h-4 w-4" /> Invoices <span className="rounded-full bg-[#D8B46A]/25 px-1.5 text-[9px]">{invoices.length}</span></button></div>

      {!isInvoices ? <SupplierGrid suppliers={suppliers} /> : <InvoiceGrid invoices={invoices} />}

      {showModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#2c1018]/55 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowModal(false); }}><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl border border-[#D8B46A]/35 bg-[#FFF9EB] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#D8B46A]">New relationship</p><h2 className="mt-1 font-playfair text-2xl font-black text-[#942E3A]">Add supplier</h2><p className="mt-1 text-xs text-[#6B1F2A]/60">Save the contact and purchasing details you will need later.</p></div><button type="button" onClick={() => setShowModal(false)} className="rounded-full p-2 text-[#942E3A] hover:bg-[#942E3A]/10" aria-label="Close"><X className="h-5 w-5" /></button></div><form action={createSupplierAction} className="mt-6 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Supplier name *</span><input required name="name" className="admin-input" placeholder="Supplier or company name" /></label><label><span className="field-label">Phone</span><input name="phone" className="admin-input" placeholder="01xxxxxxxxx" /></label><label><span className="field-label">Email</span><input name="email" type="email" className="admin-input" placeholder="name@company.com" /></label><label className="sm:col-span-2"><span className="field-label">Address</span><input name="address" className="admin-input" placeholder="City, area, warehouse address" /></label><label className="sm:col-span-2"><span className="field-label">Notes</span><textarea name="notes" rows={4} className="admin-input resize-y" placeholder="Payment terms, delivery habits, product specialties..." /></label><div className="flex flex-col-reverse gap-2 pt-2 sm:col-span-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setShowModal(false)} className="rounded-xl border border-[#942E3A]/15 bg-white px-5 py-3 text-xs font-bold text-[#942E3A]">Cancel</button><button type="submit" className="rounded-xl bg-[#942E3A] px-5 py-3 text-xs font-bold text-[#FFF9EB]">Save supplier</button></div></form></div></div>}
    </div>
  );
}

function SupplierGrid({ suppliers }: { suppliers: SupplierCard[] }) {
  if (!suppliers.length) return <EmptyState icon={<Building2 />} title="No suppliers yet" text="Add your first supplier to start tracking procurement." />;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{suppliers.map((supplier) => <div key={supplier.id} className="group relative rounded-3xl border border-[#942E3A]/10 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#D8B46A]/60 hover:shadow-md"><Link href={`/admin/suppliers/${supplier.id}`} className="absolute inset-0 rounded-3xl" aria-label={`Open ${supplier.name}`} /><div className="relative pointer-events-none flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#942E3A] text-[#D8B46A]"><Building2 className="h-5 w-5" /></div><form action={deleteSupplierAction} className="pointer-events-auto"><input type="hidden" name="id" value={supplier.id} /><button type="submit" aria-label={`Delete ${supplier.name}`} className="rounded-lg p-2 text-red-600 opacity-70 transition hover:bg-red-50 hover:opacity-100"><Trash2 className="h-4 w-4" /></button></form></div><h2 className="relative mt-5 font-playfair text-xl font-bold text-[#942E3A]">{supplier.name}</h2><div className="relative mt-3 space-y-1.5 text-[11px] text-[#6B1F2A]/65"><p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5 text-[#D8B46A]" />{supplier.phone || "No phone added"}</p><p className="flex items-center gap-2 truncate"><Mail className="h-3.5 w-3.5 shrink-0 text-[#D8B46A]" />{supplier.email || "No email added"}</p><p className="flex items-center gap-2"><MapPin className="h-3.5 w-3.5 text-[#D8B46A]" />{supplier.address || "No address added"}</p></div><div className="relative mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-[#FFF9EB] p-3"><p className="text-[9px] uppercase tracking-wide text-[#6B1F2A]/50">Products</p><p className="mt-1 font-playfair text-xl font-black text-[#942E3A]">{supplier.productCount}</p></div><div className="rounded-2xl bg-[#fff7df] p-3"><p className="text-[9px] uppercase tracking-wide text-[#6B1F2A]/50">Invoices</p><p className="mt-1 font-playfair text-xl font-black text-[#942E3A]">{supplier.invoiceCount}</p></div></div><p className="relative mt-4 text-[10px] font-bold text-[#D8B46A]">Purchases: {formatCurrency(supplier.invoiceTotal)}</p></div>)}</div>;
}

function InvoiceGrid({ invoices }: { invoices: InvoiceCard[] }) {
  if (!invoices.length) return <EmptyState icon={<FileText />} title="No invoices yet" text="Create a purchase invoice to receive stock and record its cost." />;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{invoices.map((invoice) => <Link key={invoice.id} href={`/admin/suppliers/invoices/${invoice.id}`} className="rounded-3xl border border-[#942E3A]/10 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#D8B46A]/60 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#fff7df] text-[#942E3A]"><FileText className="h-5 w-5" /></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-bold text-emerald-700">Paid</span></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.18em] text-[#D8B46A]">{invoice.invoiceNumber}</p><h2 className="mt-1 font-playfair text-xl font-bold text-[#942E3A]">{invoice.supplierName}</h2><p className="mt-2 text-xs text-[#6B1F2A]/60">{new Date(invoice.invoiceDate).toLocaleDateString("en-US", { dateStyle: "medium" })} · {invoice.itemCount} line items</p><div className="mt-5 flex items-end justify-between border-t border-[#942E3A]/10 pt-4"><span className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/50">Total invoice</span><strong className="font-playfair text-xl text-[#942E3A]">{formatCurrency(invoice.total)}</strong></div></Link>)}</div>;
}

function EmptyState({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-3xl border border-dashed border-[#D8B46A]/60 bg-white p-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff7df] text-[#D8B46A]">{icon}</div><h2 className="mt-4 font-playfair text-xl font-bold text-[#942E3A]">{title}</h2><p className="mt-1 text-xs text-[#6B1F2A]/60">{text}</p></div>; }
