import Link from "next/link";
import { Building2, FileText, Mail, MapPin, Phone, Package } from "lucide-react";
import { notFound } from "next/navigation";
import prisma from "@/lib/prisma";
import { requireAdmin } from "@/lib/adminAuth";
import { formatCurrency } from "@/lib/utils";
import AdminBackButton from "@/components/AdminBackButton";

export const dynamic = "force-dynamic";

export default async function SupplierDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin();
  const { id } = await params;
  const supplier = await prisma.supplier.findUnique({ where: { id }, include: { products: { include: { variants: { select: { stock: true } } }, orderBy: { name: "asc" } }, invoices: { include: { items: true }, orderBy: { invoiceDate: "desc" } } } });
  if (!supplier) notFound();
  const totalPurchases = supplier.invoices.reduce((sum, invoice) => sum + Number(invoice.total), 0);
  const totalUnits = supplier.invoices.reduce((sum, invoice) => sum + invoice.items.reduce((items, item) => items + item.quantity, 0), 0);

  return <div className="mx-auto max-w-6xl space-y-5"><div className="flex items-center gap-3"><AdminBackButton fallbackHref="/admin/suppliers" /><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#D8B46A]">Procurement profile</p><h1 className="mt-1 font-playfair text-3xl font-black">{supplier.name}</h1></div></div>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-3xl bg-[#942E3A] p-6 text-[#FFF9EB] sm:p-8"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#D8B46A] text-[#942E3A]"><Building2 /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#D8B46A]">Supplier account</p><h2 className="mt-1 font-playfair text-3xl font-black">{supplier.name}</h2></div></div><div className="mt-7 grid gap-3 text-xs sm:grid-cols-2"><div className="space-y-3 rounded-2xl bg-white/10 p-4"><p className="flex items-center gap-2"><Phone className="h-4 w-4 text-[#D8B46A]" />{supplier.phone || "No phone"}</p><p className="flex items-center gap-2 break-all"><Mail className="h-4 w-4 text-[#D8B46A]" />{supplier.email || "No email"}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#D8B46A]" />{supplier.address || "No address"}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-[#D8B46A]">Notes</p><p className="mt-2 leading-relaxed text-white/80">{supplier.notes || "No purchasing notes added yet."}</p></div></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-3xl border border-[#942E3A]/10 bg-white p-5"><FileText className="h-5 w-5 text-[#D8B46A]" /><p className="mt-5 text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Invoices</p><p className="mt-1 font-playfair text-3xl font-black text-[#942E3A]">{supplier.invoices.length}</p></div><div className="rounded-3xl border border-[#D8B46A]/35 bg-[#fff7df] p-5"><p className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Purchases</p><p className="mt-5 font-playfair text-xl font-black text-[#942E3A]">{formatCurrency(totalPurchases)}</p></div><div className="col-span-2 rounded-3xl border border-[#942E3A]/10 bg-white p-5"><p className="text-[10px] uppercase tracking-wide text-[#6B1F2A]/55">Units received</p><p className="mt-1 font-playfair text-3xl font-black text-[#942E3A]">{totalUnits}</p></div></div></section>
    <section className="rounded-3xl border border-[#942E3A]/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[#D8B46A]" /><h2 className="font-playfair text-xl font-bold">Supplier invoices</h2></div><Link href="/admin/suppliers/invoices/new" className="rounded-xl bg-[#942E3A] px-3 py-2 text-[10px] font-bold text-[#FFF9EB]">New invoice</Link></div><div className="mt-4 space-y-2">{supplier.invoices.length ? supplier.invoices.map((invoice) => <Link href={`/admin/suppliers/invoices/${invoice.id}`} key={invoice.id} className="flex flex-col gap-2 rounded-2xl border border-[#942E3A]/10 p-4 transition hover:border-[#D8B46A] sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[#942E3A]">{invoice.invoiceNumber}</p><p className="mt-1 text-[10px] text-[#6B1F2A]/60">{invoice.invoiceDate.toLocaleDateString("en-US", { dateStyle: "medium" })} · {invoice.items.length} products</p></div><div className="text-left sm:text-right"><p className="font-playfair text-lg font-bold text-[#942E3A]">{formatCurrency(Number(invoice.total))}</p></div></Link>) : <p className="py-10 text-center text-xs text-[#6B1F2A]/60">No invoices for this supplier yet.</p>}</div></section>
    <section className="rounded-3xl border border-[#942E3A]/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><Package className="h-4 w-4 text-[#D8B46A]" /><h2 className="font-playfair text-xl font-bold">Linked product catalog</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{supplier.products.length ? supplier.products.map((product) => <Link key={product.id} href={`/admin/products/${product.id}`} className="flex items-center justify-between rounded-2xl bg-[#FFF9EB] px-4 py-3 text-xs"><span className="font-bold text-[#942E3A]">{product.name}</span><span className="text-[#6B1F2A]/60">{product.variants.reduce((sum, variant) => sum + variant.stock, 0)} in stock</span></Link>) : <p className="py-8 text-center text-xs text-[#6B1F2A]/60">No products linked yet.</p>}</div></section>
  </div>;
}
